/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentMode = IDL.Variant({
  'upi' : IDL.Null,
  'bank' : IDL.Null,
  'cash' : IDL.Null,
  'cheque' : IDL.Null,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSampleData' : IDL.Func([], [], []),
  'createPlan' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'makePayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, PaymentMode], [], []),
  'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'searchStudentsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'searchStudentsByName' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'searchStudentsByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'seedPlans' : IDL.Func([], [], []),
  'seedStudents' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentMode = IDL.Variant({
    'upi' : IDL.Null,
    'bank' : IDL.Null,
    'cash' : IDL.Null,
    'cheque' : IDL.Null,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addSampleData' : IDL.Func([], [], []),
    'createPlan' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'makePayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, PaymentMode], [], []),
    'registerStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'searchStudentsByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'searchStudentsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'searchStudentsByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'seedPlans' : IDL.Func([], [], []),
    'seedStudents' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };