/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Student {
    id: bigint;
    name: string;
    email: string;
    phone: string;
}
export enum PaymentMode {
    upi = "upi",
    bank = "bank",
    cash = "cash",
    cheque = "cheque"
}
export interface backendInterface {
    addSampleData(): Promise<void>;
    createPlan(name: string, fee: bigint): Promise<bigint>;
    makePayment(studentId: bigint, planId: bigint, amountPaid: bigint, mode: PaymentMode): Promise<void>;
    registerStudent(name: string, phone: string, email: string): Promise<bigint>;
    searchStudentsByEmail(email: string): Promise<Array<Student>>;
    searchStudentsByName(name: string): Promise<Array<Student>>;
    searchStudentsByPhone(phone: string): Promise<Array<Student>>;
    seedPlans(): Promise<void>;
    seedStudents(): Promise<void>;
}
import type { PaymentMode as _PaymentMode } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSampleData();
            return result;
        }
    }
    async createPlan(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlan(arg0, arg1);
            return result;
        }
    }
    async makePayment(arg0: bigint, arg1: bigint, arg2: bigint, arg3: PaymentMode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.makePayment(arg0, arg1, arg2, to_candid_PaymentMode_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makePayment(arg0, arg1, arg2, to_candid_PaymentMode_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async registerStudent(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0, arg1, arg2);
            return result;
        }
    }
    async searchStudentsByEmail(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudentsByEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudentsByEmail(arg0);
            return result;
        }
    }
    async searchStudentsByName(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudentsByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudentsByName(arg0);
            return result;
        }
    }
    async searchStudentsByPhone(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudentsByPhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudentsByPhone(arg0);
            return result;
        }
    }
    async seedPlans(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedPlans();
            return result;
        }
    }
    async seedStudents(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedStudents();
            return result;
        }
    }
}
function to_candid_PaymentMode_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    upi: null;
} | {
    bank: null;
} | {
    cash: null;
} | {
    cheque: null;
} {
    return value == PaymentMode.upi ? {
        upi: null
    } : value == PaymentMode.bank ? {
        bank: null
    } : value == PaymentMode.cash ? {
        cash: null
    } : value == PaymentMode.cheque ? {
        cheque: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
